#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DEVTOOLS="$DIR/data/development.list"

# Install preferred development applications using the list of packages 'data/development.list'
function development {
    log_info 'Installing preferred development applications...'
    log_warning 'Requires root privileges'

    # For loop for installing
    for PACKAGE in $(cat $DEVTOOLS)
    do
        # Check if package is installed
        PKGCHECK=$(dnf list installed | grep "$PACKAGE")
        if [ "" == "$PKGCHECK" ]; then
            log_info "Package '$PACKAGE' is not installed. Installing..."
            # Install package
            sudo dnf install -y $PACKAGE
            log_success 'Done.'
        else
            log_success "Package '$PACKAGE' is installed."
        fi
    done
    log_success 'Done.'
}
