#!/usr/bin/env bash

log_error(){
    echo -e "\033[1;31m -- $@ --\033[m" 1>&2
}

log_info(){
    echo -e "\033[1;32m -- $@ --\033[0m"
}

log_warning(){
    echo -e "\033[1;33m -- $@ --\033[0m"
}

log_question(){
    echo -e "\033[1;34m -- $@ --\033[0m"
}

log_success(){
    echo -e "\033[1;35m -- $@ --\033[0m"
}

log_header(){
    echo -e "\033[1;36m -- $@ --\033[0m"
}

log_default(){
    echo -e "\033[0;37m $@ \033[0m"
}
